---
# Vagrant hostname and IP configuration.
vagrant_hostname: ilr-website.dev
vagrant_ip: 192.168.88.89

# A list of synced folders, with the keys 'local_path', 'destination', and 'id'.
vagrant_synced_folders:
  - local_path: "../ilr-website"
    destination: "/var/www/ilr-website"
    id: ilr-website
    type: nfs

# Memory and CPU to use for this VM.
vagrant_memory: 4096
vagrant_cpus: 2

# Other variables in this file will be used during Ansible provisioning.
mysql_root_password: root
drush_version: master

# Comment out any extra utilities you don't want to install.
installed_extras:
  - mailhog
  - xdebug
  - xhprof

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "443"
  - "3306"
  - "8025"
  - "8080"
  - "8443"

# Major release of drupal in use (6, 7, 8, etc.). Be sure to update the core
# version inside the drupal.make file if you change the major version here.
drupal_major_version: 7

# The path where Drupal will be downloaded and installed.
drupal_core_path: "/var/www/ilr-website/docroot"

drupal_domain: "ilr-website.dev"
drupal_site_name: "ILR Dev Site"
drupal_install_profile: ilr

# TODO - REMOVE THIS VARIABLE AFTER ANSIBLE 1.8.3+
drush_keep_updated: yes

drupal_mysql_user: drupal
drupal_mysql_password: drupal
drupal_mysql_database: ilr

apache_vhosts:
  - {servername: "{{ drupal_domain }}", documentroot: "{{ drupal_core_path }}"}
  - {servername: "local.xhprof.com", documentroot: "/usr/share/php/xhprof_html"}

php_memory_limit: "256M"
php_display_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"

# Disable main XDebug components unless needed.
php_xdebug_coverage_enable: 0
php_xdebug_default_enable: 0
