---
- name: Create Drupal database.
  mysql_db: "db={{ drupal_mysql_database }} state=present"

- name: Remove default virtualhost file.
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart webserver
