---
- name: Install extra apt packages (if any are configured).
  apt: "name={{ item }} state=installed"
  with_items: extra_apt_packages | list
  when: extra_apt_packages | length

- name: Install extra yum packages (if any are configured).
  yum: "name={{ item }} state=installed"
  with_items: extra_yum_packages | list
  when: extra_yum_packages | length
