---
- hosts: all

  vars_files:
  - vars/main.yml

  pre_tasks:
  - include: tasks/init.yml

  roles:
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.php-mysql
    - geerlingguy.php-xdebug
    - geerlingguy.php-xhprof
    - geerlingguy.composer
    - geerlingguy.drush

  tasks:
    - include: tasks/www.yml
    - include: tasks/drupal.yml
    - include: tasks/cleanup.yml
