---
- hosts: all

  vars_files:
    - ../config.yml

  pre_tasks:
    - include: tasks/init-debian.yml
      when: ansible_os_family == 'Debian'
    - include: tasks/init-redhat.yml
      when: ansible_os_family == 'RedHat'

  roles:
    # Essential roles.
    - geerlingguy.firewall
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
    - { role: geerlingguy.drupal-console, when: drupal_major_version > 7 }

    # Conditionally-installed roles.
    - { role: geerlingguy.memcached, when: '"memcached" in installed_extras' }
    - { role: geerlingguy.php-memcached, when: '"memcached" in installed_extras' }
    - { role: geerlingguy.php-xdebug, when: '"xdebug" in installed_extras' }
    - { role: geerlingguy.php-xhprof, when: '"xhprof" in installed_extras' }
    - { role: geerlingguy.phpmyadmin, when: '"phpmyadmin" in installed_extras' }
    - { role: geerlingguy.pimpmylog, when: '"pimpmylog" in installed_extras' }
    - { role: geerlingguy.daemonize, when: '"mailhog" in installed_extras' }
    - { role: geerlingguy.mailhog, when: '"mailhog" in installed_extras' }
    - { role: geerlingguy.java, when: '"solr" in installed_extras' }
    - { role: geerlingguy.solr, when: '"solr" in installed_extras' }

    # Roles for security and stability on production.
    - { role: geerlingguy.security, when: extra_security_enabled }

  tasks:
    - include: tasks/www.yml
    - include: tasks/apparmor.yml
      when: ansible_os_family == 'Debian'
    - include: tasks/drupal.yml
      when: build_from_makefile
    - include: tasks/drush-aliases.yml
    - include: tasks/extras.yml
