---
- hosts: all

  vars_files:
    - ../config.yml

  pre_tasks:
    - include: tasks/init.yml
    - include: tasks/php-versions.yml

  roles:
    # Essential roles.
    - geerlingguy.firewall
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
    - { role: geerlingguy.drupal-console, when: drupal_major_version > 7 }

    # Conditionally-installed roles.
    - { role: geerlingguy.memcached, when: '"memcached" in installed_extras' }
    - { role: geerlingguy.php-memcached, when: '"memcached" in installed_extras' }
    - { role: geerlingguy.php-xdebug, when: '"xdebug" in installed_extras' }
    - { role: geerlingguy.php-xhprof, when: '"xhprof" in installed_extras' }
    - { role: geerlingguy.phpmyadmin, when: '"phpmyadmin" in installed_extras' }
    - { role: geerlingguy.pimpmylog, when: '"pimpmylog" in installed_extras' }
    - { role: geerlingguy.daemonize, when: '"mailhog" in installed_extras' }
    - { role: geerlingguy.mailhog, when: '"mailhog" in installed_extras' }
    - { role: geerlingguy.java, when: '"solr" in installed_extras' }
    - { role: geerlingguy.solr, when: '"solr" in installed_extras' }
    - { role: tersmitten.adminer, when: '"adminer" in installed_extras' }

    # Roles for security and stability on production.
    - { role: geerlingguy.security, when: extra_security_enabled }

  tasks:
    - name: Check if Drupal is already set up.
      stat: "path={{ drupal_core_path }}/index.php"
      register: drupal_site

    - include: tasks/www.yml
    - include: tasks/mysql.yml

    # Build makefile if configured.
    - include: tasks/build-makefile.yml
      when: build_makefile

    # Install site if configured.
    - include: tasks/install-site.yml
      when: install_site

    - include: tasks/drush-aliases.yml
    - include: tasks/extras.yml
